apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-volume
              mountPath: /var/lib/registry
      volumes:
        - name: registry-volume
          persistentVolumeClaim:
            claimName: docker-registry-pvc